name: Build and Push Service B

on:
  push:
    paths:
      - "service-b/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t shradha91103/service-b:latest service-b
          docker push shradha91103/service-b:latest

