name: Update Manifests

on:
  workflow_run:
    workflows:
      - "Build and Push Service A"
      - "Build and Push Service B"
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update deployment to use latest tag
        run: |
          # Service A
          sed -i "s#image: shradha91103/service-a:.*#image: shradha91103/service-a:latest#g" k8s/service-a/deployment.yaml
          # Service B
          sed -i "s#image: shradha91103/service-b:.*#image: shradha91103/service-b:latest#g" k8s/service-b/deployment.yaml

      - name: Commit and Push
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update deployment images to latest" || echo "No changes to commit"
          git push

